export enum BLOCKCHAIN_NAME {
    ETHEREUM = 'ETH',
    BINANCE_SMART_CHAIN = 'BSC',
    POLYGON = 'POLYGON',
    AVALANCHE = 'AVALANCHE',
    MOONRIVER = 'MOONRIVER',
    HARMONY = 'HARMONY',
    FANTOM = 'FANTOM'
}
